version: "2.4"
services:
  app:
    depends_on: [ db ]
    image: "voxel51/fiftyone-teams-app:v0.1.8"
    restart: always
    ports:
      - "5151:5151"
    environment:
      - FIFTYONE_DATABASE_URI=mongodb://${FIFTYONE_DB_USERNAME}:${FIFTYONE_DB_PASSWORD}@fiftyone-teams.3g3tb.mongodb.net/?retryWrites=true&w=majority&authSource=admin
      - FIFTYONE_TEAMS_ORGANIZATION=org_xW1NbItyh3Nllwlq
      - FIFTYONE_TEAMS_CLIENT_ID=7ZUcEKGtWP02RnctvUZJQ6NqlVl5MA0c
      # use one of these variables to provide credentials for cloud storage
      # - GOOGLE_APPLICATION_CREDENTIALS=/fiftyone/google.json
      # - AWS_CONFIG_FILE=/fiftyone/aws-credentials
      # - MINIO_CONFIG_FILE=/fiftyone/minio-credentials-file
      - FIFTYONE_MEDIA_CACHE_APP_IMAGES=false
      - FIFTYONE_DATABASE_NAME=fiftyone
      - FIFTYONE_DATABASE_ADMIN=false
      - FIFTYONE_MEDIA_CACHE_SIZE_BYTES=-1
    volumes:
      - type: bind
        source: ${FIFTYONE_BASE_DIR}
        target: /fiftyone
